// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: households.sql

package repository

import (
	"context"
)

const addHousehold = `-- name: AddHousehold :one
insert into Households (name)
values ($1) returning id, name
`

func (q *Queries) AddHousehold(ctx context.Context, name string) (Household, error) {
	row := q.db.QueryRow(ctx, addHousehold, name)
	var i Household
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getAllHouseholds = `-- name: GetAllHouseholds :many
select id, name from Households
`

func (q *Queries) GetAllHouseholds(ctx context.Context) ([]Household, error) {
	rows, err := q.db.Query(ctx, getAllHouseholds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Household
	for rows.Next() {
		var i Household
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
