// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: households.sql

package repository

import (
	"context"
)

const getAllHouseholds = `-- name: GetAllHouseholds :many
select id, name from Households
`

func (q *Queries) GetAllHouseholds(ctx context.Context) ([]Household, error) {
	rows, err := q.db.QueryContext(ctx, getAllHouseholds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Household
	for rows.Next() {
		var i Household
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
