// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           int32       `json:"id"`
	Name         string      `json:"name"`
	AccountOwner pgtype.Int4 `json:"account_owner"`
	HouseholdID  pgtype.Int4 `json:"household_id"`
}

type Budget struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	HouseholdID int32       `json:"household_id"`
}

type Category struct {
	ID               int32       `json:"id"`
	Name             string      `json:"name"`
	Description      pgtype.Text `json:"description"`
	HouseholdID      int32       `json:"household_id"`
	ParentCategoryID pgtype.Int4 `json:"parent_category_id"`
}

type Household struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Transaction struct {
	ID              int32            `json:"id"`
	CreatedByUserID int32            `json:"created_by_user_id"`
	UpdatedByUserID int32            `json:"updated_by_user_id"`
	TransactionDate pgtype.Date      `json:"transaction_date"`
	Name            string           `json:"name"`
	Amount          pgtype.Numeric   `json:"amount"`
	Description     pgtype.Text      `json:"description"`
	Category        pgtype.Int4      `json:"category"`
	HouseholdID     int32            `json:"household_id"`
	IsIncome        bool             `json:"is_income"`
	AccountID       int32            `json:"account_id"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password []byte `json:"password"`
}

type Userhouseholdmapping struct {
	ID          int32 `json:"id"`
	HouseholdID int32 `json:"household_id"`
	UserID      int32 `json:"user_id"`
}
