// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users_household_mapping.sql

package repository

import (
	"context"
)

const addUserHouseholdPair = `-- name: AddUserHouseholdPair :exec
insert into UserHouseholdMapping(household_id, user_id)
values ($1, $2)
`

type AddUserHouseholdPairParams struct {
	HouseholdID int32 `json:"household_id"`
	UserID      int32 `json:"user_id"`
}

func (q *Queries) AddUserHouseholdPair(ctx context.Context, arg AddUserHouseholdPairParams) error {
	_, err := q.db.Exec(ctx, addUserHouseholdPair, arg.HouseholdID, arg.UserID)
	return err
}
